name: Backpack

source: ./docs
destination: ./_docs

images_path: /assets/img/
js_path: /assets/js/
css_path: /assets/css/

markdown: redcarpet
redcarpet:
  extensions: ["with_toc_data", "tables"]
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

sections:
  - title: Patterns
    patterns:
      - title: Grid
        topics:
          - title: Basic